version: '3'
x-commons: &commons
  networks: [internal]
  env_file: .env
  volumes:
    - ".:/app"
    - "./tests/Unit/sandbox/local/userland:/tmp"

networks:
  internal:
    
services:
  composer_install:
    image: composer
    volumes: [".:/app"]
    command: install
  test_all:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    volumes:
      - ".:/app"
      - "./tests/Unit/sandbox/local/userland:/tmp"
    env_file: .env
    networks: [internal]
    depends_on: [sftp, s3, composer_install]
  test_offline: # only local and local servers
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit --testsuite offline
    depends_on: [sftp, s3, composer_install]
  test_local:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit ./tests/Unit/LocalProviderTest.php
    depends_on: [composer_install]
  test_dropbox:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit ./tests/Unit/DropboxProviderTest.php
    depends_on: [composer_install]
  test_mega:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit ./tests/Unit/MegaProviderTest.php
    depends_on: [composer_install]
  test_gdrive:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit ./tests/Unit/GDriveProviderTest.php
    depends_on: [composer_install]
  test_sftp:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit ./tests/Unit/SFtpProviderTest.php
    depends_on: [sftp, composer_install]
  sftp:
    build: tests/Unit/Dockerfiles/server_sftp
    networks: [internal]
    ports: ["22"]
    volumes:
      - "./tests/Unit/sandbox/sftp/userland:/home/flyclone"
  test_ftp:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit ./tests/Unit/FtpProviderTest.php
  #   depends_on: [ftp, composer_install]
  # ftp:
  #   image: garethflowers/ftp-server
  #   ports: ["21"]
  #   volumes:
  #     - "./tests/Unit/sandbox/ftp/userland:/home/flyclone"
  #   environment:
  #     - FTP_USER=flyclone
  #     - FTP_PASS=d15c0v3r
  test_s3:
    <<: *commons
    build: tests/Unit/Dockerfiles/tests
    command: phpunit ./tests/Unit/S3ProviderTest.php
    depends_on: [s3, composer_install]
  s3:
    image: minio/minio
    networks: [internal]
    volumes:
      - "./tests/Unit/sandbox/s3/userland:/data"
    environment:
      - MINIO_ROOT_USER=flyclone
      - MINIO_ROOT_PASSWORD=flyclone
      - MINIO_BROWSER=off
    ports: ["9000"]
    command: server /data
